version: "3.9"
networks:
  bridge_network:
    driver: bridge
services:
  mysqldb:
    container_name: mysql_onelong_env_local
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=onelong
      - MYSQL_ROOT_PASSWORD=onelong246357
    ports:
      - 4727:3306
    networks:
      - bridge_network
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: elasticsearch_onelong_env_local
    restart: always
    environment:
      - node.name=shopdev_es
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTICSEARCH_PASSWORD}
      - xpack.security.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9321:9200
    volumes:
      - elastic_search_data:/usr/share/elasticsearch/data
    networks:
      - bridge_network
  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.0
    container_name: kibana_onelong_env_local
    environment:
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTICSEARCH_PASSWORD}
    ports:
      - 5671:5601
    networks:
      - bridge_network
    links:
      - elasticsearch
volumes:
  mysql_data:
  elastic_search_data:
# docker compose -p env_local_my_onelong -f docker-compose.env.local.yaml up -d
# docker exec -it mysql_onelong_env_local /bin/bash
# docker compose -p env_local_my_onelong down
# docker run -d -p 9000:9000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
# Portainer admin - lambada246357
